// There are 6 different types of error names returned from error object,

// Error Name	Description
// EvalError	An error has occurred in the eval() function
// RangeError	An error has occurred with a number "out of range"
// ReferenceError	An error due to an illegal reference
// SyntaxError	An error due to a syntax error
// TypeError	An error due to a type error
// URIError	An error due to encodeURI()

// various statements in error handling
// try: This statement is used to test a block of code for errors
// catch: This statement is used to handle the error
// throw: This statement is used to create custom errors.
// finally: This statement is used to execute code after try and catch regardless of the result.
